{"uid":"5b550d2bb9ad8284","name":"test_wallet_address_verification","fullName":"tests.wallet_tests.test_wallet_address_verification#test_wallet_address_verification","historyId":"eb70b0f49cb6fb65d9070422c938d34c","time":{"start":1732272402341,"stop":1732272402341,"duration":0},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x55cd3077931a <unknown>\n#1 0x55cd3028f6e0 <unknown>\n#2 0x55cd302c6dc8 <unknown>\n#3 0x55cd302c2926 <unknown>\n#4 0x55cd3030e6f6 <unknown>\n#5 0x55cd3030dd46 <unknown>\n#6 0x55cd30302203 <unknown>\n#7 0x55cd302d0cc0 <unknown>\n#8 0x55cd302d1c9e <unknown>\n#9 0x55cd30746d0b <unknown>\n#10 0x55cd3074ac92 <unknown>\n#11 0x55cd30733b3c <unknown>\n#12 0x55cd3074b807 <unknown>\n#13 0x55cd307190df <unknown>\n#14 0x55cd30768578 <unknown>\n#15 0x55cd30768740 <unknown>\n#16 0x55cd30778196 <unknown>\n#17 0x7f7e8c478609 start_thread","statusTrace":"request = <SubRequest 'driver' for <Function test_wallet_address_verification>>\n\n    @pytest.fixture(autouse=True, scope=\"function\")\n    def driver(request):\n        options = webdriver.ChromeOptions()\n    \n        # Отключение анимаций\n        options.add_argument(\"--disable-animations\")\n    \n        prefs = {\"profile.managed_default_content_settings.images\": 2}  # 2 отключает загрузку изображений\n        options.add_experimental_option(\"prefs\", prefs)\n    \n        # Прочие настройки\n        options.add_argument(\"--no-sandbox\")\n        options.add_argument(\"--window-size=1280,720\")\n        options.add_argument('--disable-dev-shm-usage')\n        options.add_argument('--disable-gpu')\n    \n        # Путь к расширению\n        # project_path = os.path.dirname(os.path.abspath(__file__))\n        # extension_path = f\"{project_path}/extension/dist/chrome\"\n    \n        # CI\n        extension_path = \"/app/extension\"\n    \n        options.add_argument(f\"--load-extension={extension_path}\")\n    \n        # Инициализация драйвера\n>       driver = webdriver.Chrome(options=options)\n\n../conftest.py:33: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py:45: in __init__\n    super().__init__(\n/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chromium/webdriver.py:66: in __init__\n    super().__init__(command_executor=executor, options=options)\n/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py:212: in __init__\n    self.start_session(capabilities)\n/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py:299: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py:354: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7fb18026aa00>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"session not created\",\"message\":\"session not created: Chrome failed to sta...wn>\\\\n#15 0x55cd30768740 \\\\u003Cunknown>\\\\n#16 0x55cd30778196 \\\\u003Cunknown>\\\\n#17 0x7f7e8c478609 start_thread\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\nE         (session not created: DevToolsActivePort file doesn't exist)\nE         (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nE       Stacktrace:\nE       #0 0x55cd3077931a <unknown>\nE       #1 0x55cd3028f6e0 <unknown>\nE       #2 0x55cd302c6dc8 <unknown>\nE       #3 0x55cd302c2926 <unknown>\nE       #4 0x55cd3030e6f6 <unknown>\nE       #5 0x55cd3030dd46 <unknown>\nE       #6 0x55cd30302203 <unknown>\nE       #7 0x55cd302d0cc0 <unknown>\nE       #8 0x55cd302d1c9e <unknown>\nE       #9 0x55cd30746d0b <unknown>\nE       #10 0x55cd3074ac92 <unknown>\nE       #11 0x55cd30733b3c <unknown>\nE       #12 0x55cd3074b807 <unknown>\nE       #13 0x55cd307190df <unknown>\nE       #14 0x55cd30768578 <unknown>\nE       #15 0x55cd30768740 <unknown>\nE       #16 0x55cd30778196 <unknown>\nE       #17 0x7f7e8c478609 start_thread\n\n/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py:229: SessionNotCreatedException","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1732272399338,"stop":1732272399340,"duration":2},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"driver","time":{"start":1732272402342,"stop":1732272402546,"duration":204},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x55cd3077931a <unknown>\n#1 0x55cd3028f6e0 <unknown>\n#2 0x55cd302c6dc8 <unknown>\n#3 0x55cd302c2926 <unknown>\n#4 0x55cd3030e6f6 <unknown>\n#5 0x55cd3030dd46 <unknown>\n#6 0x55cd30302203 <unknown>\n#7 0x55cd302d0cc0 <unknown>\n#8 0x55cd302d1c9e <unknown>\n#9 0x55cd30746d0b <unknown>\n#10 0x55cd3074ac92 <unknown>\n#11 0x55cd30733b3c <unknown>\n#12 0x55cd3074b807 <unknown>\n#13 0x55cd307190df <unknown>\n#14 0x55cd30768578 <unknown>\n#15 0x55cd30768740 <unknown>\n#16 0x55cd30778196 <unknown>\n#17 0x7f7e8c478609 start_thread\n\n","statusTrace":"  File \"/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/usr/workspace/nintondo/autotests/conftest.py\", line 33, in driver\n    driver = webdriver.Chrome(options=options)\n  File \"/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chromium/webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py\", line 212, in __init__\n    self.start_session(capabilities)\n  File \"/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py\", line 299, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"driver","time":{"start":1732272402592,"stop":1732272402788,"duration":196},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x5610ef4ef31a <unknown>\n#1 0x5610ef0056e0 <unknown>\n#2 0x5610ef03cdc8 <unknown>\n#3 0x5610ef038926 <unknown>\n#4 0x5610ef0846f6 <unknown>\n#5 0x5610ef083d46 <unknown>\n#6 0x5610ef078203 <unknown>\n#7 0x5610ef046cc0 <unknown>\n#8 0x5610ef047c9e <unknown>\n#9 0x5610ef4bcd0b <unknown>\n#10 0x5610ef4c0c92 <unknown>\n#11 0x5610ef4a9b3c <unknown>\n#12 0x5610ef4c1807 <unknown>\n#13 0x5610ef48f0df <unknown>\n#14 0x5610ef4de578 <unknown>\n#15 0x5610ef4de740 <unknown>\n#16 0x5610ef4ee196 <unknown>\n#17 0x7f330c22e609 start_thread\n\n","statusTrace":"  File \"/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/usr/workspace/nintondo/autotests/conftest.py\", line 33, in driver\n    driver = webdriver.Chrome(options=options)\n  File \"/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chromium/webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py\", line 212, in __init__\n    self.start_session(capabilities)\n  File \"/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py\", line 299, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"afterStages":[],"labels":[{"name":"feature","value":"wallet_tests address verification"},{"name":"tag","value":"@pytest.mark.usefixtures('driver')"},{"name":"parentSuite","value":"tests.wallet_tests"},{"name":"suite","value":"test_wallet_address_verification"},{"name":"host","value":"b3b395eb8b5c"},{"name":"thread","value":"9-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.wallet_tests.test_wallet_address_verification"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":5,"unknown":0,"total":7},"items":[{"uid":"8eae71b4f0661a9f","reportUrl":"https://Panda2k30.github.io/nintondo_autotests/42//#testresult/8eae71b4f0661a9f","status":"passed","time":{"start":1732271393500,"stop":1732271395759,"duration":2259}},{"uid":"feefa79edc4b17e1","reportUrl":"https://Panda2k30.github.io/nintondo_autotests/41//#testresult/feefa79edc4b17e1","status":"passed","time":{"start":1732114379385,"stop":1732114381662,"duration":2277}},{"uid":"b10c3ca5422c3451","reportUrl":"https://Panda2k30.github.io/nintondo_autotests/40//#testresult/b10c3ca5422c3451","status":"broken","statusDetails":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x55e91cc5d31a <unknown>\n#1 0x55e91c7736e0 <unknown>\n#2 0x55e91c7aadc8 <unknown>\n#3 0x55e91c7a6926 <unknown>\n#4 0x55e91c7f26f6 <unknown>\n#5 0x55e91c7f1d46 <unknown>\n#6 0x55e91c7e6203 <unknown>\n#7 0x55e91c7b4cc0 <unknown>\n#8 0x55e91c7b5c9e <unknown>\n#9 0x55e91cc2ad0b <unknown>\n#10 0x55e91cc2ec92 <unknown>\n#11 0x55e91cc17b3c <unknown>\n#12 0x55e91cc2f807 <unknown>\n#13 0x55e91cbfd0df <unknown>\n#14 0x55e91cc4c578 <unknown>\n#15 0x55e91cc4c740 <unknown>\n#16 0x55e91cc5c196 <unknown>\n#17 0x7f1d561ff609 start_thread","time":{"start":1732114014394,"stop":1732114014394,"duration":0}},{"uid":"dfdfd675f15749d5","reportUrl":"https://Panda2k30.github.io/Tests/39//#testresult/dfdfd675f15749d5","status":"passed","time":{"start":1732008748505,"stop":1732008750810,"duration":2305}},{"uid":"3fd78f1d97315bd9","reportUrl":"https://Panda2k30.github.io/Tests/38//#testresult/3fd78f1d97315bd9","status":"passed","time":{"start":1732006889468,"stop":1732006891765,"duration":2297}},{"uid":"e304fffaf5e1eb3b","reportUrl":"https://Panda2k30.github.io/Tests/37//#testresult/e304fffaf5e1eb3b","status":"passed","time":{"start":1732002710892,"stop":1732002713213,"duration":2321}}]},"tags":["@pytest.mark.usefixtures('driver')"]},"source":"5b550d2bb9ad8284.json","parameterValues":[]}